export const DUMMY_TOPICS = [
  { id: "rn-cli-introduction", title: "Introduction to React Native", totalLessons: 5 },
  { id: "rn-cli-architecture", title: "React Native Architecture", totalLessons: 7 },
  { id: "rn-cli-vs-expo", title: "React Native CLI vs Expo", totalLessons: 6 },
  { id: "rn-cli-environment-setup", title: "Environment Setup", totalLessons: 8 },
  { id: "rn-cli-project-structure", title: "Project Structure", totalLessons: 8 },
  { id: "rn-cli-metro-bundler", title: "Metro Bundler", totalLessons: 5 },
  { id: "rn-cli-app-entry", title: "App Entry Point", totalLessons: 5 },
  { id: "rn-cli-components", title: "Components", totalLessons: 9 },
  { id: "rn-cli-jsx", title: "JSX", totalLessons: 6 },
  { id: "rn-cli-props", title: "Props", totalLessons: 6 },
  { id: "rn-cli-state", title: "State", totalLessons: 7 },
  { id: "rn-cli-styling", title: "Styling", totalLessons: 8 },
  { id: "rn-cli-flexbox", title: "Flexbox", totalLessons: 8 },
  { id: "rn-cli-scroll-flatlist", title: "ScrollView & FlatList", totalLessons: 8 },
  { id: "rn-cli-user-input", title: "User Input", totalLessons: 7 },
  { id: "rn-cli-navigation", title: "Navigation", totalLessons: 9 },
  { id: "rn-cli-api-calls", title: "API Calls", totalLessons: 8 },
  { id: "rn-cli-async-storage", title: "Async Storage", totalLessons: 7 },
  { id: "rn-cli-native-modules", title: "Native Modules", totalLessons: 6 },
  { id: "rn-cli-build-release", title: "Build & Release", totalLessons: 8 },
  { id: "rn-cli-best-practices", title: "Best Practices", totalLessons: 6 },
]